### ISSUE TITLE
t\200-pl-file-ok-vms.t fails on AppVeyor

### ISSUE THREAD

**Issue by tobyink** [tobyink/p5-test-compiles#3]
Migrated from [rt.cpan.org #130165](https://rt.cpan.org/Ticket/Display.html?id=130165) (status was 'new')

Requestors:
* bdfoy@cpan.org (@briandfoy)

From bdfoy@cpan.org (@briandfoy) on 2019-07-24 17:51:05
:

In my AppVeyor builds for PerlPowerTools using Visual Studio, the t\200-pl-file-ok-vms.t test mysteriously exits with 25.

https://ci.appveyor.com/project/briandfoy/perlpowertools/build/job/2e6903j7245qck99

**Comment by briandfoy** [comment]
I forget the details of this problem, that file is no longer in the distro, and I no longer see errors in AppVeyor (or GitHub Actions). You can close this issue.
